- name: download oracle-jdk -> "{{ jdk[version]['filename'] }}" from "{{ jdk[version]['url'] }}"
  get_url:
    url: "{{ jdk[version]['url'] }}"
    dest: "{{ download_path }}/{{ jdk[version]['filename']}}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    mode: 0644
    checksum: "{{ jdk[version]['checksum'] }}"
  tags:
    - download

- name: create path -> "{{ release_path }}"
  file:
    dest: "{{ release_path }}"
    mode: 0755
    state: directory
- name: unarchive "{{ jdk[version]['filename'] }}"
  unarchive:
    src: "{{ download_path }}/{{ jdk[version]['filename'] }}"
    dest: "{{ release_path }}/"
    remote_src: yes
    mode: 0755
